### ISSUE TITLE
File path parity adjustments

### ISSUE THREAD

**Issue by break-core** [open-ead/sead#128]
Certain files in open-ead sead have incorrect paths which are not "canonical" to the original sead. The files are as follows:

## Issue 1: seadGameFrameworkNx wrong path
`include/framework/seadGameFrameworkNx.h` is incorrect. The path for the header should look more like `include/framework/nx/seadGameFrameworkNx.h`. (NOTE: The same should be done for when `seadGameFrameworkNx` is decompiled fully for C++.) This is because the end of the file name has "Nx" and as such follows the format of Cafe, CTR, and Nin specific code and will have it's own special folder. It was also confirmed by paths found in the Switch's applet code.

## Issue 2: seadFontMgr not real file
`devenv/seadFontMgr` is not an actual file in sead whatsoever. The script just handles sead's debug font stuff. In the original EAD sead, this is handled by `gfx/nvn/seadDebugFontMgrNvn.cpp`. So you can basically merge the existing stuff in seadFontMgr to seadDebugFontMgrNvn.

These are the main ones I could find (using the paths and asserts I have collected from various titles). Hopefully these can be adjusted soon.

**Comment by aboood40091** [comment]
Is there a benefit to reporting this if it has already been reported?

**Comment by MonsterDruide1** [comment]
Can be closed!
